defmodule Freyja.Effects.Else do
  @moduledoc """
  Higher-order Else effect for handling bind pattern match failures in Hefty computations.

  ## Overview

  The Else effect provides `with`-style pattern match failure handling for Hefty
  computations. When a `<-` binding or `=` assignment pattern fails to match,
  a `BindMatchFailed` effect is emitted. The `Else` higher-order effect interposes
  on these failures and routes them to handler clauses.

  ## How It Works

  1. **`BindMatchFailed`** - A first-order effect emitted when a bind pattern doesn't match
  2. **`Else`** - A higher-order effect that wraps a computation and interposes on
     `BindMatchFailed`, routing failures to handler clauses
  3. **Multi-clause continuations** - The `hefty` macro generates continuations with
     two clauses: the desired pattern, and a catch-all that emits `BindMatchFailed`

  ## Example

      hefty do
        {:ok, a} <- get_a()
        {:ok, b} <- get_b(a)
        return(a + b)
      else
        {:error, reason} -> return({:failed, reason})
        other -> return({:unhandled, other})
      end

  When `get_a()` returns `{:error, :not_found}`, it doesn't match `{:ok, a}`,
  so `BindMatchFailed` is emitted with the value `{:error, :not_found}`.
  The `Else` algebra interposes on this and routes to the matching else clause.

  ## Interaction with Catch

  `else` and `catch` are orthogonal:
  - `else` handles **pattern match failures** (via `BindMatchFailed` effect)
  - `catch` handles **thrown errors** (via `Throw` effect)

  The semantic ordering is fixed: `catch` wraps `else`, so:
  - `else` handles failures from the main computation
  - `catch` handles throws from both the main computation AND the else handler

  In source code, `else` must come before `catch`:

      hefty do
        ...
      else
        ...  # handles pattern match failures
      catch
        ...  # handles throws (including from else handler)
      end

  ## See Also

  - `Freyja.Effects.Else.Algebra` - The elaboration algebra
  - `Freyja.Effects.Catch` - Higher-order effect for exception handling
  - `Freyja.Effects.Throw` - First-order throw effects
  """

  import Freyja.Freer.Sig.DefEffectStruct
  import Freyja.Hefty.Sig.DefHeftyStruct

  alias Freyja.Freer
  alias Freyja.Hefty

  # First-order effect - signal that a bind pattern failed to match
  def_effect_struct(BindMatchFailed, [:value])

  @doc """
  Emit a bind match failure effect.

  This is called by the generated code when a complex pattern in a `<-` binding
  or `=` assignment fails to match.

  ## Parameters

  - `value` - The value that failed to match the pattern

  ## Returns

  A `Freer.Impure` node with the `BindMatchFailed` effect.

  ## Example

      # Generated by hefty macro for: {:ok, a} <- get_a()
      Hefty.bind(get_a(), fn
        {:ok, a} -> rest_of_computation
        __nomatch__ -> Lift.lift(Else.bind_match_failed(__nomatch__))
      end)
  """
  def bind_match_failed(value) do
    %BindMatchFailed{value: value} |> Freer.send_effect()
  end

  # Higher-order operation - wraps computation, handles BindMatchFailed
  def_hefty_struct(Else, [:handler_fn])

  @doc """
  Create an Else operation that wraps a computation and handles pattern match failures.

  ## Parameters

  - `inner_comp` - Hefty computation that may emit `BindMatchFailed` effects
  - `handler_fn` - Function `(failed_value -> Hefty.t())` that receives the
    non-matching value and returns a Hefty computation for recovery

  ## Returns

  A `Hefty.Impure` node with the `Else` operation and computation forks.

  ## Example

      Else.else_hefty(
        hefty do
          {:ok, a} <- get_a()
          return(a)
        end,
        fn
          {:error, reason} -> return({:failed, reason})
          other -> Lift.lift(Throw.throw_error({:bind_match_failed, other}))
        end
      )
  """
  def else_hefty(inner_comp, handler_fn) when is_function(handler_fn, 1) do
    Hefty.send_hefty(
      __MODULE__,
      %Else{handler_fn: handler_fn},
      %{inner: inner_comp}
    )
  end
end

defmodule Freyja.Effects.Else.Algebra do
  @moduledoc """
  Algebra for elaborating Else operations into first-order effects.

  ## Strategy

  The Else operation is elaborated using interposition:

  1. Take the already-elaborated inner computation (Freer)
  2. Interpose on `BindMatchFailed` effects
  3. When a `BindMatchFailed` is caught, call the handler function with the failed value
  4. Elaborate the handler's result (it returns Hefty) and bind with outer continuation
  5. The handler short-circuits - we don't continue with the original computation

  ## Key Insight

  When this algebra's `elaborate/4` is called, the inner computation in `psi`
  is already Freer (not Hefty). The fold has elaborated it bottom-up.

  However, the handler function returns Hefty, so we need to call the elaborator
  on its result before binding with the continuation.

  ## Nesting Behavior

  Inner `else` blocks handle their own `BindMatchFailed` effects. The interpose
  mechanism naturally scopes this - an inner `else` catches failures from its
  wrapped computation, outer `else` doesn't see them.
  """

  @behaviour Freyja.Hefty.Algebra

  alias Freyja.Effects.Else, as: ElseMod
  alias Freyja.Effects.Else.BindMatchFailed
  alias Freyja.Effects.Else.Else
  alias Freyja.Freer
  alias Freyja.Freer.Interpose

  @impl true
  def handles_hefty?(sig) when sig == ElseMod, do: true
  def handles_hefty?(_), do: false

  @impl true
  def elaborate(%Else{handler_fn: handler_fn}, psi, k, elaborator) do
    # Extract already-elaborated inner computation (Freer)
    inner = Map.fetch!(psi, :inner)

    # Interpose on BindMatchFailed - call handler_fn with the failed value
    # Handler returns Hefty, which we elaborate, then bind with outer continuation
    transformed =
      Interpose.interpose_with(
        inner,
        # Match only BindMatchFailed operations from this effect
        fn sig, data ->
          sig == ElseMod and match?(%BindMatchFailed{}, data)
        end,
        fn %BindMatchFailed{value: failed_val}, _original_k ->
          # When a bind match fails:
          # 1. Call the handler function to get a Hefty computation
          handler_hefty_comp = handler_fn.(failed_val)
          # 2. Elaborate the handler computation (it's Hefty, needs elaboration!)
          handler_freer_comp = elaborator.(handler_hefty_comp)
          # 3. Return the handler result directly - DON'T call k here!
          #    BindMatchFailed short-circuits, so we discard the original continuation
          #    The outer continuation k is applied once at the end via Freer.bind(transformed, k)
          handler_freer_comp
        end
      )

    # Bind the transformed computation to the outer continuation
    Freer.bind(transformed, k)
  end

  @doc """
  Add this algebra to a computation or builder pipeline.

  ## Examples

      # Start new pipeline
      hefty_computation |> Else.Algebra.run()

      # Add to existing pipeline
      builder |> Else.Algebra.run()
  """
  def run(computation_or_builder) do
    Freyja.Run.RunBuilder.add(computation_or_builder, __MODULE__, nil)
  end
end
